services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-minicrm}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - crm_network

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8787:8787"
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql://root:password@db:3306/minicrm}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      NODE_ENV: development
    volumes:
      - ./apps/api:/app
      - /app/node_modules
      - /app/prisma/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crm_network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8787}
      API_BASE_URL: ${API_BASE_URL:-http://api:8787}
      NODE_ENV: development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - crm_network

volumes:
  mysql_data:

networks:
  crm_network:
    driver: bridge